### ISSUE TITLE
Video stream not working

### ISSUE THREAD

**Issue by thorizer** [elliott-wen/Remote-Gaming#1]
The audio and controls works perfectly !
However, the client's window stays black . The server keeps updating about the ISoundComponent and controls but nothing about the IVideoComponent .

![screenshot](https://cloud.githubusercontent.com/assets/13587810/13377650/1daf223a-dde4-11e5-973b-3eeaba31df2a.PNG)

**Comment by elliott-wen** [comment]
This system relies on hooking functions for directx9 to capture the realtime images. If your game is not built on directx9, the system may fail to work. You could try the game War Craft 3 first.

**Comment by thorizer** [comment]
i m trying with the game warcraft 3 actually . i've put the d3d9.dll into the game directory

**Comment by thorizer** [comment]
also the client streams any audio from the server not only the game .
![sc2](https://cloud.githubusercontent.com/assets/13587810/13377799/4101c402-ddeb-11e5-9227-ba04cf971123.PNG)

**Comment by elliott-wen** [comment]
are you sure that the d3d9.dll is properly loaded?

**Comment by thorizer** [comment]
I don't know what is wrong with my Warcraft 3 but I've put d3d9 in the VLC directory, run a video and everything is working :dancer: 
Sorry for wasting your time

![h1](https://cloud.githubusercontent.com/assets/13587810/13378050/63453ed0-ddf6-11e5-8ec5-9edeab2c6013.PNG)
